robot:
  kinematics: 'diff'
  length: 1.6
  width: 2.0

device: cuda

train:

 # minimal PoC for learned prox + constraint loss
  direct_train: true
  model_name: diff_learned_prox_robot 
  projection: learned         # {hard|none|learned}
  use_lconstr: true
  w_constr: 0.10
  use_kkt: false
  w_kkt: 0.00
  kkt_rho: 0.50

  direct_train: true
  data_size: 100000
  data_range: [-25, -25, 25, 25]
  batch_size: 256
  epoch: 2500
  valid_freq: 50
  save_freq: 500
  lr: 5e-5
  lr_decay: 0.5
  decay_freq: 1500





