robot:
  kinematics: 'acker'
  length: 4.6
  width: 1.6
  wheelbase: 3

device: cuda

train:
  # minimal PoC for learned prox + constraint loss
  direct_train: true
  model_name: acker_CLARABEL_robot
  projection: none         # {hard|none|learned}
  use_lconstr: false
  w_constr: 0.10
  use_kkt: false
  w_kkt: 0.01
  kkt_rho: 0.50

  data_size: 100000              # extreme short sanity
  data_range: [-25, -25, 25, 25]
  batch_size: 256
  epoch: 5000
  valid_freq: 1
  save_freq: 500
  lr: 5e-5
  lr_decay: 0.5
  decay_freq: 1500

  # Early stopping
  early_stop: true
  early_stop_patience: 500
  early_stop_min_delta: 1.0e-7
  early_stop_min_epoch: 1000
  early_stop_metric: val_total


