robot:
  kinematics: 'acker'
  length: 4.6
  width: 1.6
  wheelbase: 3

device: cuda

train:
  # minimal PoC for learned prox + constraint loss
  direct_train: true
  model_name: acker_learned_prox_robot
  projection: learned         # {hard|none|learned}
  use_lconstr: true
  w_constr: 0.10
  use_kkt: false
  w_kkt: 0.01
  kkt_rho: 0.50

  data_size: 100000              # extreme short sanity
  data_range: [-25, -25, 25, 25]
  batch_size: 128
  epoch: 2500
  valid_freq: 250
  save_freq: 500
  lr: 5e-5
  lr_decay: 0.5
  decay_freq: 1500


